### ISSUE TITLE
Running `gm` with no arguments results in python exception

### ISSUE THREAD

**Issue by peterbn** [Mitra0000/Gum#22]
Running `gm` with no arguments results in 

```
Traceback (most recent call last):
  File "/usr/local/google/code/Gum/src/main.py", line 287, in <module>
    result = main(parser.getArgs())
  File "/usr/local/google/code/Gum/src/main.py", line 33, in main
    Cacher.getCachedKey("REBASE_QUEUE") is not None):
  File "/usr/local/google/code/Gum/src/cacher.py", line 48, in getCachedKey
    return cls._get()._getCachedKey(key)
  File "/usr/local/google/code/Gum/src/cacher.py", line 90, in _getCachedKey
    self.init()
  File "/usr/local/google/code/Gum/src/cacher.py", line 44, in init
    cls._get._init()
AttributeError: 'function' object has no attribute '_init'
```

I would have expected a help message to let me know what commands are available.

**Comment by Mitra0000** [comment]
This was an error relating to the cacher. It is fixed as of https://github.com/Mitra0000/Gum/commit/8ccfecd79e5eb253cc12e5f97641d79fb74e89b7. Please update using git pull.
